auto: True
drone_ids : [1]
drone1_home: [3, 2, 3]
take_off_height: 3
take_off_blocking: True
inspect: [0,0,0,6.5] # x,y,z,r

relative_angle: 1.0

waypoints: 
  - [0, 5, 9.4]
  - [5, 0, 9.4]
  - [0, -5, 9.4]
  - [-5, 0, 9.4]
  - [0, 5, 9.4]
  - [5, 0, 9.4]
  - [0, -5, 9.4]
  - [-5, 0, 9.4]
  - [0, 5, 9.4]
  - [5, 0, 9.4]
  - [0, -5, 9.4]
  - [-5, 0, 9.4]
  - [0, 5, 9.4]
  - [5, 0, 9.4]
  - [0, -5, 9.4]
  - [-5, 0, 9.4]
  - [0, 5, 9.4]
  - [5, 0, 9.4]
  - [0, -5, 9.4]
  - [-5, 0, 9.4]
  - [0, 5, 9.4]
  - [5, 0, 9.4]
  - [0, -5, 9.4]
  - [-5, 0, 9.4]
  - [0, 5, 9.4]
  - [5, 0, 9.4]
  - [0, -5, 9.4]
  - [-5, 0, 9.4]