auto: False
drone_ids : [1,2]
leader_start_point: [3, 3, 3]
follower_start_point: [3, 3, 3]
take_off_height: 2
take_off_blocking: False
inspect: [0,0,0,6.5] # x,y,z,r


relative_angle: 0.6

waypoints: 
  - [0, 5, 9]
  - [0, -3, 4]
  - [2, 3, 11]
  - [-2, -1, 6]