auto: True
leader_start_point: [3, 3, 3]
follower_start_point: [3, 3, 3]
take_off_height: 2
take_off_blocking: False
x_inspect: 0
y_inspect: 0
z_inspect: 10
r_inspect: 8

relative_angle: 0.4

n_waypoints: 4
waypoint1: [0, 5, 15]
waypoint2: [5, 0, 12]
waypoint3: [0, -5, 5]
waypoint4: [-5, 0, 9]