name: mission_planner
root: ./

windows:
  - gazebo:
      layout: even-vertical
      panes:
        - roslaunch mission_planner simulation_windmill.launch
        # - roslaunch mission_planner gazebo_world_2drones.launch
        # - roslaunch mission_planner gazebo_world_3drones.launch
  - leader:
      layout: even-vertical
      panes:
        - sleep 15; roslaunch mission_planner mission_planner.launch drone_id:=1 leader:=true
  - follower:
      layout: even-vertical
      panes:
        - sleep 15; roslaunch mission_planner mission_planner_follower.launch drone_id:=2 leader:=false
  - trajectory_follower:
      layout: even-vertical
      panes:
        - sleep 15; roslaunch trajectory_follower trajectory_follower.launch drone_id:=1
        - sleep 15; roslaunch trajectory_follower trajectory_follower.launch drone_id:=2
  # - rviz:
  #     layout: even-vertical
  #     panes:
  #       - sleep 10; roslaunch mission_planner rviz.launch
  - python script:  
      layout: even-vertical
      panes:
        - sleep 17; python mission_script.py
        # - sleep 17; python experiments.py
  - rosbag:
      layout: even-vertical
      panes:
        # - sleep 40; roslaunch mission_planner rosbag_recorder.launch
        - sleep 25; roslaunch mission_planner rosbag_recorder_experiment.launch id:=1 record_duration:=120
        - sleep 25; roslaunch mission_planner rosbag_recorder_experiment.launch id:=2 record_duration:=120
        # - sleep 25; roslaunch mission_planner rosbag_recorder_experiment.launch id:=3 record_duration:=120