name: mission_planner
root: ./

windows:
  - gazebo:
      layout: even-vertical
      panes:
        - roslaunch mission_planner simulation_windmill.launch
  - leader:
      layout: even-vertical
      panes:
        - sleep 15; roslaunch mission_planner mission_planner.launch drone_id:=1 leader:=true
  - follower:
      layout: even-vertical
      panes:
        - sleep 15; roslaunch mission_planner mission_planner_follower.launch drone_id:=2 leader:=false
  - trajectory_follower:
      layout: even-vertical
      panes:
        - sleep 15; roslaunch trajectory_follower trajectory_follower.launch drone_id:=1
        - sleep 15; roslaunch trajectory_follower trajectory_follower.launch drone_id:=2
  - rviz:
      layout: even-vertical
      panes:
        - sleep 8; roslaunch mission_planner rviz.launch
  - python script:  
      layout: even-vertical
      panes:
        - sleep 15; python mission_script.py