name: mission_planner
root: ./

windows:
  - gazebo:
      layout: even-vertical
      panes:
        # - roslaunch mission_planner simulation_windmill_2drones.launch
        - roslaunch mission_planner simulation_windmill_2drones_light.launch
  - leader:
      layout: even-vertical
      panes:
        - sleep 12; roslaunch mission_planner mission_planner.launch drone_id:=1 leader:=true
  - follower:
      layout: even-vertical
      panes:
        - sleep 13; roslaunch mission_planner mission_planner_follower.launch drone_id:=2 leader:=false
  - trajectory_follower:
      layout: even-vertical
      panes:
        - sleep 14; roslaunch trajectory_follower trajectory_follower.launch drone_id:=1
        - sleep 15; roslaunch trajectory_follower trajectory_follower.launch drone_id:=2
  # - rviz:
  #     layout: even-vertical
  #     panes:
  #       - sleep 15; roslaunch mission_planner rviz2.launch
  - python script:  
      layout: even-vertical
      panes:
        - sleep 17; python ../mission_script_2drones.py
  - rosbag:
      layout: even-vertical
      panes:
        - sleep 40; roslaunch mission_planner rosbag_recorder.launch